### ISSUE TITLE
Validation other than SHA1

### ISSUE THREAD

**Issue by DuvG62** [dazinator/AspNetCore.LegacyAuthCookieCompat#11]
I'm trying to interact with a Framework system using HMACSHA256 as a validation algorithm in its machinekey.  I need to implement single-sign-on between that Framework system and a new .NET Core 2 system.   
I have full access to the config of the Framework system, but don't want to change its existing machine key as I need to avoid logging out existing users on that system.

Any advice on how best to approach this?

**Comment by vivek-9dec** [comment]
Hi @DuvG62 - I've added support for SHA256, see pr - https://github.com/dazinator/AspNetCore.LegacyAuthCookieCompat/pull/12

**Comment by DuvG62** [comment]
Just what I needed - Thanks!

**Comment by dazinator** [comment]
thanks @vivek-9dec !
