### ISSUE TITLE
Example of implementation in .NET Core app?

### ISSUE THREAD

**Issue by ryanulit** [dazinator/AspNetCore.LegacyAuthCookieCompat#14]
Hello,

Could you add an example of how to actually use this library within a .NET Core app?  I'm confused as to what to do next after decrypting the legacy FormsAuth ticket to let .NET Core then use it correctly to set the authenticated User principal.

**Comment by dazinator** [comment]
Asp.net core has documentation on how to sign a user in. Dors this documentation help you: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.1&tabs=aspnetcore2x#create-an-authentication-cookie  ?

**Comment by dazinator** [comment]
Hmm scrap that. They dont seem to talk about TicketDataFormat.

Basically when using cookie middleware (or authentication middleware) on the cookie options you can configure a the TicketDataFormat to a custom one. This is the approach I took. This allows you to just write a custom class to work with your existing legacy cookie format. If you do this, cookie / auth middleware will handle the user sign in code for you. If you dont do this, and instead call SignInAsync to set a principal yourself, that will create a new cookie in the default format for asp.net core.

When I get time I will consider adding an example of this. Or i'll accept a PR for an example.

**Comment by dazinator** [comment]
@ryanulit - I remember posting an example of TicketDataFormat here, which might help you: https://stackoverflow.com/questions/34265117/mvc6-decrypting-a-forms-authentication-cookie-from-another-website/34422719#34422719

**Comment by ryanulit** [comment]
@dazinator - I actually found that exact stackoverflow post shortly after posting this issue, though it seems like you have since made updates to the implementation.  I came up with the following code below, which seems to be working but still need to do some more involved testing.  I will try to submit a pull request with a sample legacy webforms app and a .NET Core API at some point if possible.  Thanks!

```
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using AspNetCore.LegacyAuthCookieCompat;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace SampleDotNetCoreApi
{
    public class Startup
    {
        private string validationKey = "a_validation_key";
        private string decryptionKey = "a_decryption_key";

        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie(opt =>
                {
                    opt.TicketDataFormat = new FormsAuthCookieTicketFormat(decryptionKey, validationKey);
                    opt.Cookie.Name = ".ASPXAUTH";
                    opt.Cookie.Domain = "localhost";
                    opt.Cookie.HttpOnly = true;
                    opt.Cookie.Expiration = TimeSpan.FromMinutes(20);
                    opt.Events = new CookieAuthenticationEvents
                    {
                        OnRedirectToLogin = redirectCtx =>
                        {
                            redirectCtx.Response.StatusCode = 401;
                            return Task.CompletedTask;
                        }
                    };
                });

            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            
            app.UseAuthentication();

            app.UseMvc();
        }
    }

    public class FormsAuthCookieTicketFormat : ISecureDataFormat<AuthenticationTicket>
    {
        private LegacyFormsAuthenticationTicketEncryptor _encryptor;

        public FormsAuthCookieTicketFormat(string decryptionKey, string validationKey)
        {
            _encryptor = new LegacyFormsAuthenticationTicketEncryptor(decryptionKey, validationKey, ShaVersion.Sha1);
        }

        public string Protect(AuthenticationTicket data)
        {
            throw new NotImplementedException();
        }

        public string Protect(AuthenticationTicket data, string purpose)
        {
            throw new NotImplementedException();
        }

        public AuthenticationTicket Unprotect(string protectedText)
        {
            throw new NotImplementedException();
        }

        public AuthenticationTicket Unprotect(string protectedText, string purpose)
        {
            var ticket = _encryptor.DecryptCookie(protectedText);

            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

            var principal = new ClaimsPrincipal(identity);
            
            var authProperties = new AuthenticationProperties
            {
                IssuedUtc = ticket.IssueDate.ToUniversalTime(),
                ExpiresUtc = ticket.Expiration.ToUniversalTime(),
                IsPersistent = ticket.IsPersistent
            };

            return new AuthenticationTicket(principal, authProperties, CookieAuthenticationDefaults.AuthenticationScheme);
        }
    }
}
```

**Comment by ryanulit** [comment]
@dazinator I'm seeing that the `Protect(AuthenticationTicket data)` method in the above sample is getting called now and again, which is causing intermittent errors for me due to the `NotImplementedException`.  I'm trying to find what is calling it in the AspNetCore source code, but haven't had much luck yet.

Do you happen to know what causes Protect to fire with .NET Core Cookie Auth?

**Comment by azharuddinsayed** [comment]
I have fixed the issue and it is working fine 
i have written my own implementation 
this article is helped me a lot
thanks @dazinator
