### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sgravrock** [dazinator/AspNetCore.LegacyAuthCookieCompat#15]
Could you please clarify what license this package is available under? I couldn't find any license information in either the source code or the NuGet package metadata.

**Comment by lemoinem** [comment]
FYI: Microsoft's Reference Source is using MIT Licence as per https://github.com/microsoft/referencesource/blob/master/LICENSE.txt

@dazinator: your previous comment seems to imply MIT Licence or similar for this repo as well (correct me if I'm wrong). If MIT Licence is acceptable for you, adding it to the repo might clear up these questions (:.

**Comment by dazinator** [comment]
Thanks for the info. If anyone is willing to send a PR to add the MIT licence that would be welcomed - otherwise I'll try and get around to it at some point in the future.
