### ISSUE TITLE
UTC vs LocalTime in FormsAuthenticationTicket

### ISSUE THREAD

**Issue by lemoinem** [dazinator/AspNetCore.LegacyAuthCookieCompat#20]
The code to serialize and deserialize the `FormsAuthenticationTicket` assumes the data in `FormsAuthenticationTicket` for issue and expiration dates to be local DateTimes.

In ASP.Net old code:
https://github.com/microsoft/referencesource/blob/master/System.Web/Security/FormsAuthenticationTicketSerializer.cs:

`Serialize` has code `ticketWriter.Write(ticket.IssueDateUtc.Ticks);` and `ticketWriter.Write(ticket.ExpirationUtc.Ticks);`
`Deserialize` calls `FormsAuthenticationTicket.FromUtc`

In AspNetCore.LegacyAuthCookieCompat (class `FormsAuthenticationTicketHelper`):

`Serialize` has code `ticketWriter.Write(ticket.IssueDate.ToUniversalTime().Ticks);` and `ticketWriter.Write(ticket.Expiration.ToUniversalTime().Ticks);`
`Deserialize` calls `FormsAuthenticationTicketHelper.FromUtc`

Moreover, in old ASP.Net code, `FormsAuthenticationTicket.FromUtc` converts the `issueDateUtc` and `expirationUtc` to local time with `.ToLocalTime()` (https://github.com/microsoft/referencesource/blob/master/System.Web/Security/FormsAuthenticationTicket.cs#L228-L229)

This last step isn't done in AspNetCore.LegacyAuthCookieCompat (See https://github.com/dazinator/AspNetCore.LegacyAuthCookieCompat/blob/master/src/AspNetCore.LegacyAuthCookieCompat/FormsAuthenticationTicketHelper.cs#L129-L131).

Because of this, the issue date and expiration date of deserialized tickets is never the correct one, as it will always be UTC.

Tests didn't catch that because they incorrectly create `FormsAuthenticationTicket` with UTC DateTime instead of local ones and didn't double check the date from the tickets deserialized from legacy ASP.Net serialization.

This is a major issue as tickets will have an extended or shortened lifetime depending on which side of UTC we are.

I will be preparing a pull request fixing these issues.

**Comment by lemoinem** [comment]
Another point:
In ASP.Net code, `FormsAuthenticationTicket.Expired`, `DateTime.UtcNow` is compared to `ExpirationUtc` (See
https://github.com/microsoft/referencesource/blob/master/System.Web/Security/FormsAuthenticationTicket.cs#L61-L70), but in AspNetCore.LegacyAuthCookieCompat, `DateTime.UtcNow` is compared to `Expiration`(See https://github.com/dazinator/AspNetCore.LegacyAuthCookieCompat/blob/master/src/AspNetCore.LegacyAuthCookieCompat/FormsAuthenticationTicket.cs#L15).

This provides invalid result when the `Expiration` IS local time (as it should be).

**Comment by dazinator** [comment]
Thanks for discovering this issue and for the PR. I'll get it merged and released probably within the next day.
