### ISSUE TITLE
would like to have encryptions options to support 3Des and etc

### ISSUE THREAD

**Issue by oscarwongx** [dazinator/AspNetCore.LegacyAuthCookieCompat#31]
HI,

I'm trying to solve my issue on legacy cookie which is encrypted using method different than AES, may I know where I can find document on the original MS source code on for other methods? I would rewrite it to support additional method if possible.

**Comment by dazinator** [comment]
I worked on this a very long time ago now, but you could check reference source, this may or may not be the best location: https://github.com/microsoft/referencesource/blob/master/System.Web/Security/FormsAuthentication.cs#L276

**Comment by dazinator** [comment]
stale
