### ISSUE TITLE
Add FormsProtectionEnum support

### ISSUE THREAD

**Issue by hisomu** [dazinator/AspNetCore.LegacyAuthCookieCompat#34]
I wanted to say thank you for adding backwards compatibility support to FormAuthentication! It helped me recreate the cookie to support the other old apps.

I have a feature request to add in FormsProtectionEnum, I am currently using Validation protection. 
For example, here is the old configuration of the security settings:
`<authentication mode="Forms">
<forms name=".ASPXFORMSDEMO" requireSSL="true" protection="Validation" loginUrl="/" timeout="120" slidingExpiration="true" />
</authentication>`

In the asp.net FormsAuthentication it only encrypts the cookie if the Protection is not Validation: https://github.com/microsoft/referencesource/blob/master/System.Web/Security/FormsAuthentication.cs#L276

**Comment by dazinator** [comment]
thanks @hisomu - have merged the PR
