### ISSUE TITLE
Trouble decrypting cookie

### ISSUE THREAD

**Issue by jonathantower** [dazinator/AspNetCore.LegacyAuthCookieCompat#5]
I very much like your approach and would like to use your nuget package, but I'm trying to decrypt a formsauth cookie generated from an existing application and getting an error with the SHA1 validation here:

```
if (isHashAppended)
{
	// need to check the hash signature, and strip it off the end of the byte array.
	cookieBlob = hasher.CheckHashAndRemove(cookieBlob);
	if (cookieBlob == null)
	{
		// signature verification failed
		throw new Exception();
	}
}
```

I'm using the code below to attempt the decryption:
```
string validationKey = "aaaaa";
string decryptionKey = "bb";
byte[] decryptionKeyBytes = HexUtils.HexToBinary(decryptionKey);
byte[] validationKeyBytes = HexUtils.HexToBinary(validationKey);

var legacyFormsAuthenticationTicketEncryptor = 
	new LegacyFormsAuthenticationTicketEncryptor(decryptionKeyBytes, validationKeyBytes);

FormsAuthenticationTicket decryptedFormsAuthenticationTicket =
	legacyFormsAuthenticationTicketEncryptor.DecryptCookie("value from the right of .ASPXAUTH= in the cookie");
```

And grabbed the validation key (aaaaa) and decryption key (bb) from the existing app's web.config:
```
<machineKey validationKey="aaaaa" decryptionKey="bb" validation="SHA1" decryption="AES" />
    <authentication mode="Forms">
```

The exisiting app is create the cookie like this:
```
FormsAuthentication.SetAuthCookie("username", false);
```

Any thoughts?

**Comment by dazinator** [comment]
May I ask, are you able to put together a sample that produces the cookie that cannot be decrypted? 

My suspicion is that, things maybe slightly different depending on the version of the target framework you are running on. The cookies I tested with were all produced by web applications targeting 
Net 3.5. If targeting .net 4 or 4.5 I think the encryption process might have subtle quirks related to those frameworks that this project may not cater for. Not saying this is true, just a suspicion at this point.

**Comment by dazinator** [comment]
Also, off the top of my head, I dont remember having to skip .ASPXAUTH= might be worth double checking if that bit is necessary or if you can pass that in.

**Comment by dazinator** [comment]
You could also try running the unit test, putting a break point in that problematic bit of code to see what is happening there when its working smoothly. It might reveal something further about the nature of the problem.

**Comment by jonathantower** [comment]
Thanks for the feedback, @dazinator. I looked at what was happening vs how the unit test worked, and wasn't sure what the differences were. I did create a sample app to reproduce the issue, though. 

https://github.com/jonathantower/aspnet-legacy-auth-issue

If you start up both sites in Visual Studio, click on the login button on the "legacy" one, then click on the link to hit the .NET Core site and it will try to parse the cookie and get the exception I mentioned.

**Comment by BjoernBeeli** [comment]
I had the same problem using this great package in my environment.
`cookieBlob = hasher.CheckHashAndRemove(cookieBlob);` returned null 

Reason: I defined first machineKey explicit with compatibilityMode="Framework45", which is not supported by the package. After changing the compatibilityMode to "Framework20SP2" every thing works for me.
It seems that it implements only the old mode.

**Comment by PaddoSwam** [comment]
I'm on it! :)

**Comment by dazinator** [comment]
Any update on this, can i close?

**Comment by dazinator** [comment]
Closing as per comment from @BjoernBeeli - let me know if I need to reopen
