### ISSUE TITLE
asp.net 4.5

### ISSUE THREAD

**Issue by rajkumars82** [dazinator/AspNetCore.LegacyAuthCookieCompat#9]
Hi - I am using this package to generate a encrypted cookie value and match the value created in ASP.NET 4.5. Is ASP.NET 4.5 is supported by this library ? Please advice.

**Comment by dazinator** [comment]
I am not certain, I have only tested this against an asp.net 3.5 personally. Id you do try it, please report back.

**Comment by dazinator** [comment]
@rajkumars82  did you manage to get any further on this?

**Comment by dazinator** [comment]
Any updates?

**Comment by carlosganzerla** [comment]
> Hi - I am using this package to generate a encrypted cookie value and match the value created in ASP.NET 4.5. Is ASP.NET 4.5 is supported by this library ? Please advice.

I'm trying the same thing. When I try to decrypt the cookie value I'm always getting the Signature verification failed exception. I doubled checked and both apps are using the same keys. The ASP. NET 4 app keys are defined in the web.config machineKey section. Does this make any difference? It shouldn't, but it seems that there may be some incompatibility.

**Comment by dazinator** [comment]
Are you able to add a repro to this to the unit tests to demonstrate the issue?

**Comment by dazinator** [comment]
@carlosganzerla what version of the nuget package are you using?

**Comment by carlosganzerla** [comment]
@dazinator Currently 1.2.1

**Comment by dazinator** [comment]
Ok just checking it was the latest. I am afraid I won't have time to look into this at the moment. However if you are able to provide a repro by adding to the tests showing the failure to decrypt a .NET 45 generated machine and validation key (obviously this can be a new one you have generate for the purposes of the test, and not your actual keys!) - then I promise to look into it at some point in the future, or perhaps someone else can pick it up.

**Comment by carlosganzerla** [comment]
It turned out that setting the compatibility mode to Framework20SP2 solved it. I also believe that this is the necessary configuration to make it compatible with further versions of ASP .NET

**Comment by dazinator** [comment]
@carlosganzerla Thanks.
If this project has helped you, and you manage to find any time, please consider submitting a PR to the README to mention your discovery and help anyone else who tries to run on .NET 45!
Glad you found a solution!

**Comment by gallivantor** [comment]
The machinekey encryption changed in .NET 4.5:
https://blogs.msdn.microsoft.com/webdev/2012/10/23/cryptographic-improvements-in-asp-net-4-5-pt-2/
it is probably this change that causes the failure (presumably the adding of the Purpose field which would need to be checked too) but yes as a short-term workaround changing the compat mode to Framework20SP2 seems to solve it

**Comment by cveld** [comment]
Also for cookies generated by the .NET Framework 4.5 scheme there is an open source library available that enables you to consume these legacy cookies into your ASP.NET Core application. The developers have used the .NET Framework reference implementation to build their own Machinekey based encryption/decryption logic. See https://github.com/synercoder/FormsAuthentication

**Comment by sgf** [comment]
> Also for cookies generated by the .NET Framework 4.5 scheme there is an open source library available that enables you to consume these legacy cookies into your ASP.NET Core application. The developers have used the .NET Framework reference implementation to build their own Machinekey based encryption/decryption logic. See https://github.com/synercoder/FormsAuthentication

im tested that project,can't got the correct Claim

**Comment by lemoinem** [comment]
@dazinator I encountered the same issue. However, switching back to Framework20SP2 compatibility mode wasn't an option for us. synercoder/FormsAuthentication wasn't fitting either as we use custom Ticket version number and userData, which they don't support. 

After some investigation, including reading some code from I found the microsoft referencesource and synercoder's code (both are open source).

Here is the list of the modifications I had to make:
- Key derivation: In ASP.Net 4.5, the keys in machineKey aren't used as-is to encrypt and verify tickets/cookies, but need an additional intermediary steps.
- IV/AES Mode implementation: The proper way to deal with padding and IV when decrypting/encrypting changed: no CBC Mode, IV must be extracted prior to decryption, no postprocessing.
- Hash Checking after decryption: This isn't done anymore in ASP. So we don't need to do it.

All the modifications can be done within LegacyFormsAuthenticationTicketEncryptor, I'd add a new option, equivalent to the selection of a compatibility mode.
I have currently only tested decryption of cookies generated by an ASP.Net 4.5 app.
But my next step will clearly be to check for encryption as well.

Would you be opened to either do the modifications or accept a PR?

**Comment by dazinator** [comment]
@lemoinem sure I'd welcome a PR for this.
